spring:
  application:
    name: TranslaterBot

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/weather
#    username: test
#    password: test
#
#  jpa:
#    database: postgresql
#    show-sql: true
#
#  liquibase:
#    change-log: db/changelog/main/main-changelog.yml

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

yandex:
  catalog:
    id: ${YANDEX_CATALOG_ID}
  oauth:
    token: ${YANDEX_OAUTH_TOKEN}
